name: Deploy Dev
on:
  push:
    branches:
      - main
env:
  NODE_ENV: dev
  ENV_NAME: dev

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Heroku deploy
      run: git push https://heroku:c748c7f4-8d18-4ef1-9bee-2d95ae689595@git.heroku.com/destillery.git main -f
  